version: '2.3'

services:
    milvus-admin:
      image: milvusdb/milvus-em:latest
      depends_on:
        - milvus
      links:
        - milvus
      ports:
        - "9093:80"
      networks:
        jeeai-faceid:
          aliases:
            - milvusadmin
      restart: always

#    mongo-express:
#      image: mongo-express
#      ports:
#        - 9075:8081
#      environment:
#        - ME_CONFIG_MONGODB_SERVER=mongo
#        - ME_CONFIG_MONGODB_PORT=27017
#        - ME_CONFIG_MONGODB_ADMINUSERNAME=dps
#        - ME_CONFIG_MONGODB_ADMINPASSWORD=dps123
#      networks:
#        jeeai-faceid:
#          aliases:
#            - mongo-express
#      restart: always

    portainer:
      image: portainer/portainer
      ports:
        - "9100:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      restart: always

volumes:
  prometheus_data: {}
  grafana_data: {}
  portainer_data: {}

networks:
    jeeai-faceid:
      external: true
