FROM tiangolo/uvicorn-gunicorn:python3.8-alpine3.10

ARG REST_HOST
ARG REST_PORT
ARG REST_SECRET_KEY
ARG KEYDB_HOST
ARG KEYDB_PORT
ARG KEYDB_PASSWORD
ARG KEYDB_CACHE_DB
ARG KEYDB_DONE_SESSION_DB
ARG KEYDB_REGISTER_DB
ARG KAFKA_BOOTSTRAP_SERVERS
ARG KAFKA_DETECTOR_TOPIC
ARG MILVUS_HOST
ARG MILVUS_PORT
ARG MONGODB_HOST
ARG MONGODB_PORT
ARG MONGODB_USER
ARG MONGODB_PASSWORD
ARG MONGODB_DATABASE
ARG KAFKA_UPDATER_TOPIC

ENV KAFKA_UPDATER_TOPIC=${KAFKA_UPDATER_TOPIC}
ENV REST_HOST=${REST_HOST}
ENV REST_PORT=${REST_PORT}
ENV REST_SECRET_KEY=${REST_SECRET_KEY}
ENV KEYDB_HOST=${KEYDB_HOST}
ENV KEYDB_PORT=${KEYDB_PORT}
ENV KEYDB_PASSWORD=${KEYDB_PASSWORD}
ENV KEYDB_CACHE_DB=${KEYDB_CACHE_DB}
ENV KEYDB_DONE_SESSION_DB=${KEYDB_DONE_SESSION_DB}
ENV KEYDB_REGISTER_DB=${KEYDB_REGISTER_DB}
ENV KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
ENV KAFKA_DETECTOR_TOPIC=${KAFKA_DETECTOR_TOPIC}
ENV MILVUS_HOST=${MILVUS_HOST}
ENV MILVUS_PORT=${MILVUS_PORT}
ENV MONGODB_HOST=${MONGODB_HOST}
ENV MONGODB_PORT=${MONGODB_PORT}
ENV MONGODB_USER=${MONGODB_USER}
ENV MONGODB_PASSWORD=${MONGODB_PASSWORD}
ENV MONGODB_DATABASE=${MONGODB_DATABASE}

RUN apk add gcc g++
RUN apk add cmake clang clang-dev make gcc g++ libc-dev linux-headers

RUN pip install --upgrade pip
RUN pip install --no-cache-dir fastapi
RUN pip install grpcio==1.23.0
RUN pip install grpcio-tools==1.23.0
RUN pip install redis==3.5.3
RUN pip install kafka-python==2.0.1
RUN pip install gunicorn==20.0.4
RUN pip install pymongo==3.10.1
RUN pip install uvicorn==0.11.5
RUN pip install numpy==1.18.5
RUN pip install pymilvus==0.2.13
RUN pip install python-multipart==0.0.5
RUN pip install Cython
RUN pip install scikit-build

ENV PYTHONPATH=/app
